### ISSUE TITLE
Migrate mcr_trajectory_time_parameterizer to kinetic

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_common_robotics#3]
@sthoduka @deebuls can you guys ask someone from @b-it-bots/work to help migrate this? Maybe @abhishek098 can help? The @home guys have taken care of the rest of the packages (I think we're missing just one)

**Comment by sthoduka** [comment]
yes, @abhishek098 or @DjoleMNE?

**Comment by abhishekpadalkar** [comment]
It is not migrated. Work in Progess

**Comment by DjoleMNE** [comment]
We made changes. It is building correctly now. Abhishek will push now.

**Comment by sthoduka** [comment]
#9 closes this
