### ISSUE TITLE
Refactoring mcr_environments

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_common_robotics#37]
Since we are using the stable setup in @home, we cannot save the environments in the development workspace. One possible way to handle this is making this package an independent repository, the other one I can think of is creating `mdr_environments` and `mir_environments` but I think this defeats the purpose of having a common environment.

In addition to that, moving all the gazebo-related things to `mas_simulation` makes more sense. Thoughts?

**Comment by jcmayoral** [comment]
I agree, as you said, to migrate gazebo related stuff to mas_simulation, so it is not needed anymore to add simulation related packages to any robots. Regarding the mcr_default_env_config, it might be a good idea to create a mas_config (or other name) repository, not just for environment config but we could add even navigation config files, maybe creating branches for simulation/real robot.

**Comment by moriarty** [comment]
@argeno - related to splitting out `mas_simulation` you may also want to split out the:

`mas_common_robotics/mcr_common/mcr_description` package into it's own repository.

This way, the simulation packages, and real robot packages would get the meshes and URDF files from the same location, and not need all of `mas_common_robotics`

If a student wanted to simulate one of the `b-it-bots` robots, without running the RoboCup code, they currently need to have both `mas_common_robotics` and `mas_industrial_robotics` or `mas_domestic_robotics` to get all of the required URDF and meshes. 

But it might be useful, to be able to run "pure" robot, either in simulation or on hardware, which would just bring in the minimal dependencies.
