### ISSUE TITLE
Remove dependency to mcr_perception_msgs

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_common_robotics#45]
Seems like `mcr_algorithms` depends on `mcr_perception_msgs` only for the laser segmentation, couple of questions:

a) is this still being used? 
b) should this be moved to `mas_perception` instead?

**Comment by alex-mitrevski** [comment]
This definitely looks like something that would go into `mas_perception`, but it only makes sense to move it there if it's being used at all; otherwise, we could just move it to the museum, right?
